// Copyright (C) 2025  darkoned12000
// SPDX-License-Identifier: GPL-3.0-or-later
// Part of the ltheory-old-test modernization effort (Revamp Work).
// See NOTICE and LICENSE.GPL. Original engine (c) Josh Parnell, public domain.

import * as fs from 'fs';
import * as path from 'path';

// Schema of script/ltsl-lsp/api-database.json, generated by
// script/ltsl-lsp/tools/dump_api.cpp from the engine reflection registries.
// See docs/LTSL-LSP-IMPLEMENTATION-GUIDE.md for the documented shape.

export interface APIParameter {
  name: string;
  type: string;
}

export interface APIFunction {
  name: string;
  signature: string;
  returnType: string;
  parameters: APIParameter[];
  documentation: string;
  source: string;
}

export interface APIField {
  name: string;
  type: string;
}

export interface APIType {
  name: string;
  description: string;
  fields: APIField[];
  methods: APIFunction[];
  documentation: string;
}

// The engine emits overloads (and aliases) as separate entries sharing a name,
// so we index name -> APIFunction[] rather than the single-entry Map in the
// guide.
export class APIDatabase {
  private functionsByName = new Map<string, APIFunction[]>();
  private typesByName = new Map<string, APIType>();
  private allFunctions: APIFunction[] = [];
  private allTypes: APIType[] = [];

  get functionCount(): number {
    return this.allFunctions.length;
  }

  get typeCount(): number {
    return this.allTypes.length;
  }

  loadFromFile(filePath: string): void {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
    this.loadFromObject(data);
  }

  loadFromObject(data: {
    functions?: APIFunction[];
    types?: APIType[];
  }): void {
    for (const fn of data.functions ?? []) {
      this.allFunctions.push(fn);
      const arr = this.functionsByName.get(fn.name);
      if (arr) {
        arr.push(fn);
      } else {
        this.functionsByName.set(fn.name, [fn]);
      }
    }
    for (const type of data.types ?? []) {
      this.allTypes.push(type);
      this.typesByName.set(type.name, type);
    }
  }

  /** All overloads registered under `name` (empty when unknown). */
  getFunctions(name: string): APIFunction[] {
    return this.functionsByName.get(name) ?? [];
  }

  getFunction(name: string): APIFunction | undefined {
    return this.getFunctions(name)[0];
  }

  getType(name: string): APIType | undefined {
    return this.typesByName.get(name);
  }

  isFunctionName(name: string): boolean {
    return this.functionsByName.has(name);
  }

  isTypeName(name: string): boolean {
    return this.typesByName.has(name);
  }

  getAllFunctions(): APIFunction[] {
    return this.allFunctions;
  }

  getAllTypes(): APIType[] {
    return this.allTypes;
  }

  /** Unique function names matching a case-sensitive prefix. */
  functionNamesMatching(prefix: string): string[] {
    const seen = new Set<string>();
    const names: string[] = [];
    for (const fn of this.allFunctions) {
      if (fn.name.startsWith(prefix) && !seen.has(fn.name)) {
        seen.add(fn.name);
        names.push(fn.name);
      }
    }
    return names.sort();
  }

  typeNamesMatching(prefix: string): string[] {
    const names: string[] = [];
    for (const type of this.allTypes) {
      if (type.name.startsWith(prefix)) {
        names.push(type.name);
      }
    }
    return names.sort();
  }
}

export function resolveDatabasePath(): string | null {
  const candidates: string[] = [];
  const env = process.env.LTSL_API_DATABASE;
  if (env) {
    candidates.push(env);
  }
  // Compiled server lives at <proj>/out/server.js; db sits next to project.
  candidates.push(path.join(__dirname, '..', 'api-database.json'));
  candidates.push(path.join(process.cwd(), 'api-database.json'));
  // Fall back to walking up from the workspace looking for script/ltsl-lsp.
  let dir = process.cwd();
  for (let i = 0; i < 6 && dir !== path.parse(dir).root; ++i) {
    candidates.push(path.join(dir, 'script', 'ltsl-lsp', 'api-database.json'));
    dir = path.dirname(dir);
  }
  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) {
      return candidate;
    }
  }
  return null;
}
